### ISSUE TITLE
incorrect interface

### ISSUE THREAD

**Issue by KaiserKarel** [gofrs/flock#33]
Flock does not exactly follow the sync.Locker interface, as it's Lock() method returns an error. sync.Mutex panics in certain occasions. I think we could have a version of flock which also panics instead of returning errors, to ensure we have the correct interface.

**Comment by theckman** [comment]
I think panics being an intentional design decision in an interface is not a good choice, and isn't something I'd personally want to support. If you'd like to work with that interface instead, I think it's better to write a shim that wraps the `flock` library, versus complicating this package further.

**Comment by KaiserKarel** [comment]
Either way seems fine to me. There are way more things that may panic with filelocks, so I get the aversion to panics. Simply fixing the Readme removes confusion as well.

Will close since I don't think much can be said, more of a sematics problem.

**Comment by KaiserKarel** [comment]
Either way seems fine to me. There are way more things that may panic with filelocks, so I get the aversion to panics. Simply fixing the Readme removes confusion as well.
